name: Aktualizacja i Publikacja Mapy
on:
  schedule:
    - cron: '0 0 * * *' # Codziennie o północy
  workflow_dispatch: 

permissions:
  contents: write # Pozwala botowi wysyłać zmiany do kodu

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pobranie kodu
        uses: actions/checkout@v3

      - name: Instalacja Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Pobierz najnowsze punkty InPost
        run: |
          mkdir -p public
          # Udajemy przeglądarkę, żeby InPost nie wysłał pustego pliku
          curl -f -L -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" \
          "https://api-pl-points.easypack24.net/v1/points?per_page=20000&types=paczkomat" -o public/paczkomaty.json
          
          # Sprawdzenie czy plik nie jest pusty
          [ -s public/paczkomaty.json ] || { echo "Plik jest pusty!"; exit 1; }

      - name: Instalacja zależności i Build projektu
        run: |
          npm install
          npm run build

      - name: Zapisz dane w repozytorium (main)
        run: |
          git config --global user.name 'InPost Bot'
          git config --global user.email 'bot@github.com'
          git add public/paczkomaty.json
          git commit -m "Automatyczna aktualizacja danych InPost [skip ci]" || exit 0
          git push origin main

      - name: Deploy na GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # UWAGA: Jeśli używasz Vite, zmień na 'dist'
          branch: gh-pages # Tutaj robot wysyła gotową stronę